// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: foundation/proto/product/v1/product.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price             int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	BuyerRewardPoints int32                  `protobuf:"varint,5,opt,name=buyer_reward_points,json=buyerRewardPoints,proto3" json:"buyer_reward_points,omitempty"` // author_reward_points is internal and not exposed.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_foundation_proto_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetBuyerRewardPoints() int32 {
	if x != nil {
		return x.BuyerRewardPoints
	}
	return 0
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_foundation_proto_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_foundation_proto_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductList) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_foundation_proto_product_v1_product_proto_rawDescGZIP(), []int{3}
}

var File_foundation_proto_product_v1_product_proto protoreflect.FileDescriptor

const file_foundation_proto_product_v1_product_proto_rawDesc = "" +
	"\n" +
	")foundation/proto/product/v1/product.proto\x12\n" +
	"product.v1\"\x95\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12.\n" +
	"\x13buyer_reward_points\x18\x05 \x01(\x05R\x11buyerRewardPoints\" \n" +
	"\x0eProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\vProductList\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\"\a\n" +
	"\x05Empty2\x8b\x01\n" +
	"\x0eProductService\x12=\n" +
	"\n" +
	"GetProduct\x12\x1a.product.v1.ProductRequest\x1a\x13.product.v1.Product\x12:\n" +
	"\fListProducts\x12\x11.product.v1.Empty\x1a\x17.product.v1.ProductListB6Z4soda-interview/foundation/proto/product/v1;productv1b\x06proto3"

var (
	file_foundation_proto_product_v1_product_proto_rawDescOnce sync.Once
	file_foundation_proto_product_v1_product_proto_rawDescData []byte
)

func file_foundation_proto_product_v1_product_proto_rawDescGZIP() []byte {
	file_foundation_proto_product_v1_product_proto_rawDescOnce.Do(func() {
		file_foundation_proto_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foundation_proto_product_v1_product_proto_rawDesc), len(file_foundation_proto_product_v1_product_proto_rawDesc)))
	})
	return file_foundation_proto_product_v1_product_proto_rawDescData
}

var file_foundation_proto_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_foundation_proto_product_v1_product_proto_goTypes = []any{
	(*Product)(nil),        // 0: product.v1.Product
	(*ProductRequest)(nil), // 1: product.v1.ProductRequest
	(*ProductList)(nil),    // 2: product.v1.ProductList
	(*Empty)(nil),          // 3: product.v1.Empty
}
var file_foundation_proto_product_v1_product_proto_depIdxs = []int32{
	0, // 0: product.v1.ProductList.products:type_name -> product.v1.Product
	1, // 1: product.v1.ProductService.GetProduct:input_type -> product.v1.ProductRequest
	3, // 2: product.v1.ProductService.ListProducts:input_type -> product.v1.Empty
	0, // 3: product.v1.ProductService.GetProduct:output_type -> product.v1.Product
	2, // 4: product.v1.ProductService.ListProducts:output_type -> product.v1.ProductList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_foundation_proto_product_v1_product_proto_init() }
func file_foundation_proto_product_v1_product_proto_init() {
	if File_foundation_proto_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foundation_proto_product_v1_product_proto_rawDesc), len(file_foundation_proto_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foundation_proto_product_v1_product_proto_goTypes,
		DependencyIndexes: file_foundation_proto_product_v1_product_proto_depIdxs,
		MessageInfos:      file_foundation_proto_product_v1_product_proto_msgTypes,
	}.Build()
	File_foundation_proto_product_v1_product_proto = out.File
	file_foundation_proto_product_v1_product_proto_goTypes = nil
	file_foundation_proto_product_v1_product_proto_depIdxs = nil
}
