// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: foundation/proto/soda-finance/v1/finance.proto

package financev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SodaPoints    int64                  `protobuf:"varint,2,opt,name=soda_points,json=sodaPoints,proto3" json:"soda_points,omitempty"`
	SodaBalance   int64                  `protobuf:"varint,3,opt,name=soda_balance,json=sodaBalance,proto3" json:"soda_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_foundation_proto_soda_finance_v1_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_soda_finance_v1_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_foundation_proto_soda_finance_v1_finance_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Wallet) GetSodaPoints() int64 {
	if x != nil {
		return x.SodaPoints
	}
	return 0
}

func (x *Wallet) GetSodaBalance() int64 {
	if x != nil {
		return x.SodaBalance
	}
	return 0
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_foundation_proto_soda_finance_v1_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_soda_finance_v1_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_foundation_proto_soda_finance_v1_finance_proto_rawDescGZIP(), []int{1}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConvertRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Ideally we specify how many points to convert, or just "convert all possible".
	// The requirements say "ConvertPoints(ConvertRequest) returns (Wallet)".
	// It implies a trigger. I'll add an amount field just in case, or leave it empty if it's "convert all".
	// Re-reading requirements: "Threshold: ONLY allowed if soda_points > 1000".
	// It doesn't say "convert X points". Usually it's "convert all eligible" or a specific amount.
	// I'll add `amount_points` to be safe, but make it optional logic-wise.
	PointsToConvert int64 `protobuf:"varint,2,opt,name=points_to_convert,json=pointsToConvert,proto3" json:"points_to_convert,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_foundation_proto_soda_finance_v1_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_soda_finance_v1_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_foundation_proto_soda_finance_v1_finance_proto_rawDescGZIP(), []int{2}
}

func (x *ConvertRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConvertRequest) GetPointsToConvert() int64 {
	if x != nil {
		return x.PointsToConvert
	}
	return 0
}

var File_foundation_proto_soda_finance_v1_finance_proto protoreflect.FileDescriptor

const file_foundation_proto_soda_finance_v1_finance_proto_rawDesc = "" +
	"\n" +
	".foundation/proto/soda-finance/v1/finance.proto\x12\x0fsoda_finance.v1\"e\n" +
	"\x06Wallet\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vsoda_points\x18\x02 \x01(\x03R\n" +
	"sodaPoints\x12!\n" +
	"\fsoda_balance\x18\x03 \x01(\x03R\vsodaBalance\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x0eConvertRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x11points_to_convert\x18\x02 \x01(\x03R\x0fpointsToConvert2\x9f\x01\n" +
	"\x0eFinanceService\x12B\n" +
	"\tGetWallet\x12\x1c.soda_finance.v1.UserRequest\x1a\x17.soda_finance.v1.Wallet\x12I\n" +
	"\rConvertPoints\x12\x1f.soda_finance.v1.ConvertRequest\x1a\x17.soda_finance.v1.WalletB;Z9soda-interview/foundation/proto/soda-finance/v1;financev1b\x06proto3"

var (
	file_foundation_proto_soda_finance_v1_finance_proto_rawDescOnce sync.Once
	file_foundation_proto_soda_finance_v1_finance_proto_rawDescData []byte
)

func file_foundation_proto_soda_finance_v1_finance_proto_rawDescGZIP() []byte {
	file_foundation_proto_soda_finance_v1_finance_proto_rawDescOnce.Do(func() {
		file_foundation_proto_soda_finance_v1_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foundation_proto_soda_finance_v1_finance_proto_rawDesc), len(file_foundation_proto_soda_finance_v1_finance_proto_rawDesc)))
	})
	return file_foundation_proto_soda_finance_v1_finance_proto_rawDescData
}

var file_foundation_proto_soda_finance_v1_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_foundation_proto_soda_finance_v1_finance_proto_goTypes = []any{
	(*Wallet)(nil),         // 0: soda_finance.v1.Wallet
	(*UserRequest)(nil),    // 1: soda_finance.v1.UserRequest
	(*ConvertRequest)(nil), // 2: soda_finance.v1.ConvertRequest
}
var file_foundation_proto_soda_finance_v1_finance_proto_depIdxs = []int32{
	1, // 0: soda_finance.v1.FinanceService.GetWallet:input_type -> soda_finance.v1.UserRequest
	2, // 1: soda_finance.v1.FinanceService.ConvertPoints:input_type -> soda_finance.v1.ConvertRequest
	0, // 2: soda_finance.v1.FinanceService.GetWallet:output_type -> soda_finance.v1.Wallet
	0, // 3: soda_finance.v1.FinanceService.ConvertPoints:output_type -> soda_finance.v1.Wallet
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foundation_proto_soda_finance_v1_finance_proto_init() }
func file_foundation_proto_soda_finance_v1_finance_proto_init() {
	if File_foundation_proto_soda_finance_v1_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foundation_proto_soda_finance_v1_finance_proto_rawDesc), len(file_foundation_proto_soda_finance_v1_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foundation_proto_soda_finance_v1_finance_proto_goTypes,
		DependencyIndexes: file_foundation_proto_soda_finance_v1_finance_proto_depIdxs,
		MessageInfos:      file_foundation_proto_soda_finance_v1_finance_proto_msgTypes,
	}.Build()
	File_foundation_proto_soda_finance_v1_finance_proto = out.File
	file_foundation_proto_soda_finance_v1_finance_proto_goTypes = nil
	file_foundation_proto_soda_finance_v1_finance_proto_depIdxs = nil
}
