// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: foundation/proto/referral-blog/v1/referral_blog.proto

package referral_blogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId        string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	LinkedProductId string                 `protobuf:"bytes,4,opt,name=linked_product_id,json=linkedProductId,proto3" json:"linked_product_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blog) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Blog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Blog) GetLinkedProductId() string {
	if x != nil {
		return x.LinkedProductId
	}
	return ""
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBlogRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateBlogRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type BlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogRequest) Reset() {
	*x = BlogRequest{}
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogRequest) ProtoMessage() {}

func (x *BlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogRequest.ProtoReflect.Descriptor instead.
func (*BlogRequest) Descriptor() ([]byte, []int) {
	return file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescGZIP(), []int{2}
}

func (x *BlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlogList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*Blog                `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogList) Reset() {
	*x = BlogList{}
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogList) ProtoMessage() {}

func (x *BlogList) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogList.ProtoReflect.Descriptor instead.
func (*BlogList) Descriptor() ([]byte, []int) {
	return file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescGZIP(), []int{3}
}

func (x *BlogList) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescGZIP(), []int{4}
}

var File_foundation_proto_referral_blog_v1_referral_blog_proto protoreflect.FileDescriptor

const file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDesc = "" +
	"\n" +
	"5foundation/proto/referral-blog/v1/referral_blog.proto\x12\x10referral_blog.v1\"y\n" +
	"\x04Blog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12*\n" +
	"\x11linked_product_id\x18\x04 \x01(\tR\x0flinkedProductId\"i\n" +
	"\x11CreateBlogRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\"\x1d\n" +
	"\vBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\bBlogList\x12,\n" +
	"\x05blogs\x18\x01 \x03(\v2\x16.referral_blog.v1.BlogR\x05blogs\"\a\n" +
	"\x05Empty2\xdc\x01\n" +
	"\vBlogService\x12I\n" +
	"\n" +
	"CreateBlog\x12#.referral_blog.v1.CreateBlogRequest\x1a\x16.referral_blog.v1.Blog\x12@\n" +
	"\tListBlogs\x12\x17.referral_blog.v1.Empty\x1a\x1a.referral_blog.v1.BlogList\x12@\n" +
	"\aGetBlog\x12\x1d.referral_blog.v1.BlogRequest\x1a\x16.referral_blog.v1.BlogBBZ@soda-interview/foundation/proto/referral-blog/v1;referral_blogv1b\x06proto3"

var (
	file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescOnce sync.Once
	file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescData []byte
)

func file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescGZIP() []byte {
	file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescOnce.Do(func() {
		file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDesc), len(file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDesc)))
	})
	return file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDescData
}

var file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_foundation_proto_referral_blog_v1_referral_blog_proto_goTypes = []any{
	(*Blog)(nil),              // 0: referral_blog.v1.Blog
	(*CreateBlogRequest)(nil), // 1: referral_blog.v1.CreateBlogRequest
	(*BlogRequest)(nil),       // 2: referral_blog.v1.BlogRequest
	(*BlogList)(nil),          // 3: referral_blog.v1.BlogList
	(*Empty)(nil),             // 4: referral_blog.v1.Empty
}
var file_foundation_proto_referral_blog_v1_referral_blog_proto_depIdxs = []int32{
	0, // 0: referral_blog.v1.BlogList.blogs:type_name -> referral_blog.v1.Blog
	1, // 1: referral_blog.v1.BlogService.CreateBlog:input_type -> referral_blog.v1.CreateBlogRequest
	4, // 2: referral_blog.v1.BlogService.ListBlogs:input_type -> referral_blog.v1.Empty
	2, // 3: referral_blog.v1.BlogService.GetBlog:input_type -> referral_blog.v1.BlogRequest
	0, // 4: referral_blog.v1.BlogService.CreateBlog:output_type -> referral_blog.v1.Blog
	3, // 5: referral_blog.v1.BlogService.ListBlogs:output_type -> referral_blog.v1.BlogList
	0, // 6: referral_blog.v1.BlogService.GetBlog:output_type -> referral_blog.v1.Blog
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_foundation_proto_referral_blog_v1_referral_blog_proto_init() }
func file_foundation_proto_referral_blog_v1_referral_blog_proto_init() {
	if File_foundation_proto_referral_blog_v1_referral_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDesc), len(file_foundation_proto_referral_blog_v1_referral_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foundation_proto_referral_blog_v1_referral_blog_proto_goTypes,
		DependencyIndexes: file_foundation_proto_referral_blog_v1_referral_blog_proto_depIdxs,
		MessageInfos:      file_foundation_proto_referral_blog_v1_referral_blog_proto_msgTypes,
	}.Build()
	File_foundation_proto_referral_blog_v1_referral_blog_proto = out.File
	file_foundation_proto_referral_blog_v1_referral_blog_proto_goTypes = nil
	file_foundation_proto_referral_blog_v1_referral_blog_proto_depIdxs = nil
}
