// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID        string `json:"id"`
	AuthorID  string `json:"author_id"`
	Content   string `json:"content"`
	ProductID string `json:"product_id"`
}

type Order struct {
	ID        string             `json:"id"`
	BuyerID   string             `json:"buyer_id"`
	ProductID string             `json:"product_id"`
	BlogID    string             `json:"blog_id"`
	Amount    int64              `json:"amount"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	Description        string `json:"description"`
	Price              int64  `json:"price"`
	BuyerRewardPoints  int32  `json:"buyer_reward_points"`
	AuthorRewardPoints int32  `json:"author_reward_points"`
}

type Transaction struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Type           string             `json:"type"`
	Amount         int64              `json:"amount"`
	RelatedOrderID pgtype.Text        `json:"related_order_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	UserID      string `json:"user_id"`
	SodaPoints  int64  `json:"soda_points"`
	SodaBalance int64  `json:"soda_balance"`
}
