// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddBalance(ctx context.Context, arg AddBalanceParams) (Wallet, error)
	AddPoints(ctx context.Context, arg AddPointsParams) (Wallet, error)
	ConvertPointsToBalance(ctx context.Context, arg ConvertPointsToBalanceParams) (Wallet, error)
	CountOrdersByBuyer(ctx context.Context, buyerID string) (int64, error)
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateWallet(ctx context.Context, userID string) (Wallet, error)
	GetBlog(ctx context.Context, id string) (Blog, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetWallet(ctx context.Context, userID string) (Wallet, error)
	ListBlogs(ctx context.Context) ([]Blog, error)
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
